#encoding: utf-8
lang_dict = {
"OurSettings": "Datos de la Empresa",
"Our Settings": "Datos de la Empresa",
"Code": "Codigo",
"Name": "Nombre",
"FantasyName": "Nombre de Fantasia",
"Fantasy Name": "Nombre de Fantasia",
"Address": "Direccion",
"City": "Ciudad",
"ZipCode": "Codigo Postal",
"Zip Code": "Codigo Postal",
"Phone": "Telefono",
"StartDate": "Inicio de Actividades",
"Start Date": "Inicio de Actividades",
"LegalInfo": "Informacion Legal",
"Legal Info": "Informacion Legal",
"Geo": "Geoposicion",
"ShortCode": "Codigo Corto",
"Short Code": "Codigo Corto",
"SalesTarget": "Objetivo de Ventas",
"Sales Target": "Objetivo de Ventas",
"BranchLabel": "Clasificacion de Sucursal",
"Branch Label": "Clasificacion de Sucursal",
"PriceDeal": "Acuerdo de Precios",
"Price Deal": "Acuerdo de Precios",
"DiscountDeal": "Acuerdo de Descuentos",
"Discount Deal": "Acuerdo de Descuentos",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",
"": "",



}

