#encoding: utf-8
#coding: utf-8
lang_dict = {
"SystemSettings": "Opciones del Sistema",
"UseUpperCaseCode": "Usar Mayusculas en Campos Codigo",
"ThousandSep": "Separador de Miles",
"DecimalSep": "Separador de Decimales",
"DateFormat": "Formato de Fecha",
"DateSep": "Separador de Fechas",
"InterpolateReportLines": "Intercalar color en lineas de reportes",
"DocumentHandling": "Documentos",
"Pre-Printed": "Pre-Impreso",
"Blank Paper":"Papel en Blanco",
"ErrorReport": "Reporte de Errores",
"EventLog": "Log de Eventos",
"LogSettings": "Opciones de Historia de Registros",
"Simple": "Sencillo",
"Version Logging": "Logueo con Versiones",
"SerNrControl": "Control de Numeros Seriales",
"Company": "Empresas",
"Code": "Codigo",
"Name": "Nombre",
"Host": "Servidor (Host)",
"Port": "Puerto",
"User": "Usuario",
"Password": u"Contraseña",
"DBName": "Base de Datos",
"DBEngine": "Motor de Base de Datos",
"PosSerNr": "Punto de Venta",
"OurSettings": "Datos de la Empresa",
"Our Settings": "Datos de la Empresa",
"FantasyName": "Nombre de Fantasia",
"Fantasy Name": "Nombre de Fantasia",
"Address": "Direccion",
"City": "Ciudad",
"ZipCode": "Codigo Postal",
"Zip Code": "Codigo Postal",
"Phone": "Telefono",
"StartDate": "Inicio de Actividades",
"Start Date": "Inicio de Actividades",
"LegalInfo": "Informacion Legal",
"Legal Info": "Informacion Legal",
"Geo": "Geoposicion",
"Office": "Sucursal",
"ShortCode": "Codigo Corto",
"Short Code": "Codigo Corto",
"SalesTarget": "Objetivo de Ventas",
"Sales Target": "Objetivo de Ventas",
"BranchLabel": "Clasificacion de Sucursal",
"Branch Label": "Clasificacion de Sucursal",
"PriceDeal": "Acuerdo de Precios",
"Price Deal": "Acuerdo de Precios",
"DiscountDeal": "Acuerdo de Descuentos",
"Discount Deal": "Acuerdo de Descuentos",
"AccessGroup": "Grupos de Acceso",
"Modules": "Modulos",
"Records": "Registros",
"Reports": "Reportes",
"Routines": "Rutinas",
"ModuleAccess": "Acceso a Modulos",
"RecordAccess": "Acceso a Registros",
"ReportAccess": "Acceso a Reportes",
"RoutineAccess": "Acceso a Rutinas",
"By Default Without Access": "Por Defecto sin Acceso",
"By Default With Total Access": "Por Defecto con Acceso Total",
"Denied": "Denegado",
"Allowed": "Permitido",
"View Only": "Solo Vista",
"View and Print": "Vista e Impresion",
"View, Print and Export": "Mostrar, Imprimir y Exportar",
"Module": "Modulo",
"Access": "Acceso",
"Visibility": "Visibilidad",
"Only Record of My Office": "Solo Registros de la Sucursal",
"All Records": "Todos los Registros",
"Holiday": "Feriados",

}

